function submit()
  addpath('./lib');

  conf.assignmentSlug = 'multi-class-classification-and-neural-networks';
  conf.itemName = 'Multi-class Classification and Neural Networks';
  conf.partArrays = { ...
    { ...
      '1', ...
      { 'lrCostFunction.m' }, ...
      'Regularized Logistic Regression', ...
    }, ...
    { ...
      '2', ...
      { 'oneVsAll.m' }, ...
      'One-vs-All Classifier Training', ...
    }, ...
    { ...
      '3', ...
      { 'predictOneVsAll.m' }, ...
      'One-vs-All Classifier Prediction', ...
    }, ...
    { ...
      '4', ...
      { 'predict.m' }, ...
      'Neural Network Prediction Function' ...
    }, ...
  };
  conf.output = @output;

  submitWithConfiguration(conf);
end